version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./app:/usr/src/app
    networks:
      - app_network
secrets:
  my_secret:
    file: ./secrets/my_secret.txt
networks:
  app_network:
    driver: bridge

