name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 14

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Run npm audit
        run: npm audit
        
      - name: Run tests
        run: npm test

  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Run staging tests
        run: npm run test:staging

  deploy:
    runs-on: ubuntu-latest
    needs: [build, staging] # Зависит от выполнения build и staging
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Build with version
        run: echo "Building version $BUILD_VERSION"
        
      - name: Deploy application
        run: npm run deploy -- --version $BUILD_VERSION
        env:
          BUILD_VERSION: ${{ github.run_number }}
